routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth\login');
});

Auth::routes();


Route::get('/home', 'HomeController@index')->name('home');
Route::get('/search','HomeController@search');


Route::resource('blogs', 'BlogController');

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = [
        'title', 'description','content','document_no','created_by','document'
      ];
      
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $blogs = Blog::latest()->paginate(5);
       return view ('blogs.index',compact('blogs'))->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blogs.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'content' => 'required',
        ]);

        Blog::create($request->all());

        return redirect()->route('blogs.index')
                        ->with('success','Blog created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        return view('blogs.show',compact('blog'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        return view('blogs.edit',compact('blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Blog $blog)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'content' => 'required',
        ]);

        $blog->update($request->all());

        return redirect()->route('blogs.index')
                        ->with('success','Blog updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        $blog->delete();

        return redirect()->route('blogs.index')
                        ->with('success','Blogs deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
    public function search(Request $request){
        $search = $request->get('search');
        $posts=DB::table('blogs')->where('title','like','%'.$search.'%')->paginate(5);
        return view('home',['posts'=> $posts]);

    }
}

resources/views/blogs/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New Policy</h2>
        </div>
        <div class="pull-right">
             <a   type="button" class="btn btn-primary " href="{{ route('blogs.index') }}">   <span uk-icon="arrow-left"></span> Back</a>  
          
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Warning!</strong> Please check your input code<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('blogs.store') }}" method="POST">
    @csrf
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <input type="text" name="title" class="form-control" placeholder="Title">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Document No:</strong>
                    <input type="text" name="document_no" class="form-control" placeholder="Document No">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        <input type="text" name="description" class="form-control" placeholder="Description">
                    </div>
                </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                <textarea class="form-control" id="summary-ckeditor" name="content"></textarea>
            </div>
        </div> 
        <textarea class="form-control"   name="created_by" style="visibility:hidden">  {{ Auth::user()->name }} </textarea>
        <input type="file" name="document" id="fileToUpload">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>

    <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
    <script>
    CKEDITOR.replace( 'summary-ckeditor' );
    </script>
</form>
@endsection

resources/views/blogs/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Blog</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('blogs.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Warning!</strong> Please check input field code<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('blogs.update',$blog->id) }}" method="POST">
        @csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Title:</strong>
                    <input type="text" name="title" value="{{ $blog->title }}" class="form-control" placeholder="Title">
                </div>
            </div>

        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Document No:</strong>
                    <input type="text" name="document_no" class="form-control" placeholder="Document No"  value="{{ $blog->document_no }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>Description:</strong>
                        <input type="text" name="description" class="form-control" placeholder="Description"  value="{{ $blog->description }}">
                    </div>
                </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Content:</strong>
                    <textarea class="form-control" style="height:150px"  id="summary-ckeditor" name="content" placeholder="Content">{{ $blog->content }}</textarea>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

        <script src="{{ asset('vendor/unisharp/laravel-ckeditor/ckeditor.js') }}"></script>
        <script>
        CKEDITOR.replace( 'summary-ckeditor' );
        </script>
    </form>
@endsection

resources/views/blogs/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>RFC POLICY REPOSITORY</h2>
            </div>
            <div class="pull-right">
                <a  type="button" class="btn btn-success" href="{{ route('blogs.create') }}"> Create new Repository</a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>Policy ID</th>
            <th>Document No</th>
            <th>Title</th>
            <th>Description</th>
            <th width="250px">Action</th>
        </tr>
        @foreach ($blogs as $blog)
        <tr>
            <td>{{ $blog->id }}</td>
            <td>{{ $blog->document_no }}</td>
            <td>{{ $blog->title }}</td>
            <td>{{ $blog->title }}</td>
            <td>
                <form action="{{ route('blogs.destroy',$blog->id) }}" method="POST">

                    <a type="button" class="btn btn-info" href="{{ route('blogs.show',$blog->id) }}">Show</a>

                    <a type="button" class="btn btn-primary" href="{{ route('blogs.edit',$blog->id) }}">Edit</a>

                    @csrf
                    @method('DELETE')

                    <button type="submit" class="btn btn-danger" style="border-radius: 0 !important; border-style: groove;">Delete</button>
                    
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    

    {!! $blogs->links() !!}

@endsection

resources/views/blogs/layout.blade.php
<!DOCTYPE html>
<html>
<head>
<title>Main layout page </title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</head>
<body>

<div class="container">
    @yield('content')
</div>
<div class="jumbotron text-center" style="margin-bottom:0">
  <p>Footer</p>
</div>
</body>
</html>

resources/views/blogs/show.blade.php
@extends('layouts.app')


@section('content')
<div class="row">
    <div class="large-9 large-centered columns">
    <h1 class="entry-title">{!! $blog->title !!}</h1>

    <div class="entry-meta">
    <span class="posted-on">Uploaded on : <a href="#" rel="bookmark"><time class="entry-date published">   {!! ($blog->created_at) !!}</time></a>	</span></div><!-- .entry-meta -->

    </div>

</div>

<div class="row">

    <div class="large-9 large-centered columns">
            <hr>
            <div class="uk-box-shadow-bottom uk-box-shadow-small uk-width-7-15@s" >
                <div class="uk-background-default uk-padding-large">
                    <p style="text-align: center;"><strong>  {!! ($blog->content) !!}</strong></p>
                    <hr>
                            <div class="uk-background-default uk-padding-small uk-width-1-2@s" style="border-style: inset;position:relative;left:49%">
                            <b><i>RESOURCES</i></b>
                             <ul><li class="pdfbutton b20">
                            [PDF] <a href="https://www.officialgazette.gov.ph/downloads/2019/11nov/20191115-EO-95-RRD.pdf">Executive Order No. 95, s. 2019</a>
                           </ul>
                            </div>
                </div>

                </div>
            </div>

    </div>

</div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')



@section('content')


<div class="row" style="margin-bottom:5%" >
        <div class="col-xs-12 col-sm-12 col-md-12" >
            <div class="input-group md-form form-sm form-2 pl-0" >
                    <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                      <span class="input-group-text red lighten-3" id="basic-text1"><i class="fas fa-search text-grey"
                          aria-hidden="true"></i> <a href="#"uk-search-icon></a></span>
                    </div>
            </div>

        </div>
  </div>
  <div class="row" style="margin-bottom:10%;left:40%;position:relative" >
      <h3><span uk-icon="icon:  file-text; ratio: 3" style="color:rgb(18,39,58)"></span>POLICIES REPOSITORY</h3>
  </div>
    @php

$model = DB::table('blogs')->simplePaginate(5);
    @endphp
  @foreach($model  as $blog)


  <div class="row"  >

      <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">

              <h1><a href="{{ route('blogs.show',$blog->id) }}" style="text-decoration: none;">{!! $blog->title !!}</a></h1>
          </div>
         </div>

      <div class="col-xs-12 col-sm-12 col-md-12">

          <div class="form-group">
              <hr>
              <strong>Description:</strong>
              {!! ($blog->description) !!}

          </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-12">
          <div class="form-group">
              <strong>Created At:</strong>

              {!! ($blog->created_at) !!}

          </div>
          <hr>
      </div>
  </div>
  @endforeach
<div style="float:right">
    {{ $model->links() }}
    <br>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{  ('RFC Repository Policies') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/css/uikit.min.css" />
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.2.3/dist/js/uikit-icons.min.js"></script>

</head>
<style>#navbar{
    background-color:rgb(18,39,58);
    color:green;}
    .watermark {
        position: absolute;
        left: 0;
        bottom: 10%;
        width: 80%;
        background-color:yellow;
        color: white;
        text-align: center;
     }
     .uk-offcanvas-bar
     {
        background-color:rgb(18,39,58);
        color:white;}
</style>
<body>
    <div id="app" >
        <nav class="navbar navbar-expand-md  shadow-sm" id="navbar">
                @include('layouts\sidebar')
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->email }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="container" style="margin-top:3%">

            @yield('content')

        </main>
    </div>
</body>
<footer style=" margin-top: 5%;">
        @include('layouts\footer')
</footer>
</html>

resources/views/layouts/footer.blade.php
@yield('js')
<style>
        .footer {
           position: fixed;
           left: 0;
           bottom: 0;
           width: 100%;
           background-color:rgb(18,39,58);
           color: white;
           text-align: center;
        }
        </style>
<div class="footer">
       <h5 style="visibility:hidden">s</h5>
</div>

resources/views/layouts/sidebar.blade.php
<button class="uk-button uk-button-default"  uk-icon="menu" type="button" style="background-color:#E5DFDF" uk-toggle="target: #offcanvas-nav"></button>



<div id="offcanvas-nav" uk-offcanvas="overlay: false;bg-close:false;">

        <div class="uk-offcanvas-bar">
                <button class="uk-offcanvas-close" type="button" uk-close></button>


            <ul class="uk-nav uk-nav-default">
                    <span class="uk-margin-medium-right" uk-icon="user"> </span>:


                    <hr>
                <li ><a href="{{ route('home')}}"><span class="uk-margin-small-right" uk-icon="icon: home"></span>HOME</a></li>
                <li ><a href="{{ url('/blogs')}}"><span class="uk-margin-small-right" uk-icon="icon: table"></span> Manage Repository Policy</a></li>
                <li ><a href="#"><span class="uk-margin-small-right" uk-icon="icon: users"></span> Users Management</a></li>
                <li ><a href="#"><span class="uk-margin-small-right" uk-icon="icon: settings"></span> System Management</a></li>
                <li ><a href="#"><span class="uk-margin-small-right" uk-icon="icon: tablet-landscape"></span> Users Activity</a></li>
                </li>

                 <div class="watermark">
                        <h5  style="color:red;text-align:center;margin-top:5%">RFC REPOSITORY POLICIES </h5>
                 </div>
            </ul>

        </div>
    </div>